# Generated by Django 2.1.7 on 2019-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Paternity Leave', 'Paternity Leave'), ('Loss of Pay', 'Loss of Pay'), ('Relocation Leave', 'Relocation Leave')], max_length=30)),
                ('days', models.IntegerField()),
                ('remark', models.CharField(max_length=30)),
                ('approver', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=6)),
                ('leave_type', models.CharField(max_length=30)),
                ('preivous_balance', models.IntegerField()),
                ('total', models.IntegerField()),
                ('used', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
