# Generated by Django 2.1.7 on 2019-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=30)),
                ('employee', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('mobile', models.CharField(max_length=30)),
                ('manager', models.CharField(choices=[('1000', '1000'), ('1010', '1010'), ('1020', '1020'), ('1020', '1020'), ('1030', '1030')], max_length=30)),
                ('primary_skill', models.CharField(choices=[('Python', 'Python'), ('C#', 'C#'), ('Perl', 'Perl'), ('Java', 'Java')], max_length=30)),
                ('designation', models.CharField(choices=[('Trainee Engineer', 'Trainee Engineer'), ('Software Engineer', 'Software Engineer'), ('Lead Engineer', 'Lead Engineer'), ('Analyst', 'Analyst'), ('Admin', 'Admin')], max_length=30)),
                ('qual', models.CharField(choices=[('BE', 'BE'), ('ME', 'ME'), ('MTech', 'MTech')], max_length=30)),
            ],
        ),
    ]
