# Generated by Django 2.1.7 on 2019-07-27 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 7, 27, 17, 54, 50, 57785)),
        ),
        migrations.AddField(
            model_name='profile',
            name='doj',
            field=models.DateField(default=datetime.datetime(2019, 7, 27, 17, 54, 50, 57808)),
        ),
    ]
