# Generated by Django 2.1.7 on 2019-07-28 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190727_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 7, 28, 17, 16, 2, 678597)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doj',
            field=models.DateField(default=datetime.datetime(2019, 7, 28, 17, 16, 2, 678618)),
        ),
    ]
