# Generated by Django 2.1.7 on 2019-10-12 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190803_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 10, 12, 3, 4, 33, 69115)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doj',
            field=models.DateField(default=datetime.datetime(2019, 10, 12, 3, 4, 33, 69137)),
        ),
    ]
