# Generated by Django 2.1.7 on 2020-02-08 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20191012_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 2, 8, 4, 7, 39, 960114)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 2, 8, 4, 7, 39, 960140)),
        ),
    ]
