# Generated by Django 2.1.7 on 2019-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetdata',
            name='holiday',
        ),
        migrations.AddField(
            model_name='timesheetdata',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
