# Generated by Django 2.1.7 on 2019-07-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20190728_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheetData',
            new_name='TimeSheetDataNew',
        ),
    ]
