# Generated by Django 2.1.7 on 2019-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_auto_20190728_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
                ('hours', models.IntegerField()),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSheetDataNew',
        ),
    ]
